<?xml version="1.0"?>
<package>
	<name>iod_calc</name>
	<version>1.0.0</version>
	<description>Interocular calibration post-processor.</description>
	<maintainer email="tes77@case.edu">Tom Shkurti</maintainer>
	<!--What is roadprintz's code licensed as? TODO Out of roadprintz license any more.-->
	<license>LicenseRef-RoadPrintz-Proprietary</license>
	
	<buildtool_depend>catkin</buildtool_depend>
	
	<build_depend>roscpp</build_depend>	<run_depend>roscpp</run_depend>
	
	<export></export>
</package>
